#!/usr/bin/env bash
#
# init-secrets.sh — generate a .env with two random secrets for a fresh
# PowerDNS-UI deployment.
#
# Idempotent: refuses to overwrite an existing .env so a re-run cannot
# silently destroy live secrets (which would make every encrypted setting
# in the DB unreadable).
#
set -euo pipefail

ENV_FILE="${1:-.env}"

if [[ -e "$ENV_FILE" ]]; then
  echo "Refusing to overwrite existing $ENV_FILE." >&2
  echo "If you genuinely need to rotate, back it up first and remove it." >&2
  exit 1
fi

if ! command -v openssl >/dev/null 2>&1; then
  echo "openssl not found on PATH. Install it or set the secrets by hand." >&2
  exit 1
fi

AUTH_SECRET="$(openssl rand -hex 32)"
APP_SECRET="$(openssl rand -hex 32)"

cat > "$ENV_FILE" <<EOF
# Generated by scripts/init-secrets.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ").
#
# AUTH_SECRET signs session JWTs. Safe to rotate (logs users out).
# APP_SECRET derives the encryption key for stored secrets (LDAP password,
#   OIDC client secret, PowerDNS API key). DO NOT rotate without re-entering
#   every encrypted setting via the Settings UI — losing it is destructive.
#
# Keep this file out of version control. Permissions are set to 600.

AUTH_SECRET=${AUTH_SECRET}
APP_SECRET=${APP_SECRET}
EOF

chmod 600 "$ENV_FILE"
echo "Wrote $ENV_FILE with random AUTH_SECRET and APP_SECRET (chmod 600)."
